http:
  port: 8080

admin:
  port: 9876
  host: localhost

apiEndpoints:
  authRegister:
    host: localhost
    paths: '/auth/register'
  authLogin:
    host: localhost
    paths: '/auth/login'
  bookingCreate:
    host: localhost
    paths: '/booking-ticket/create'
  bookingMyBookings:
    host: localhost
    paths: '/booking-ticket/my-bookings'
  bookingAllBookings:
    host: localhost
    paths: '/booking-ticket/all-bookings'
  bookingCancel:
    host: localhost
    paths: '/booking-ticket/cancel/*'
  theaterApi:
    host: localhost
    paths: '/theater/*'
  showtimeApi:
    host: localhost
    paths: '/showtime/*'
  paymentInitiate:
    host: localhost
    paths: '/payment/initiate'
  paymentConfirm:
    host: localhost
    paths: '/payment/confirm'
serviceEndpoints:
  authService:
    url: 'http://localhost:3001'
  bookingService:
    url: 'http://localhost:3002'
  theaterService:
    url: 'http://localhost:3003'
  paymentService:
    url: 'http://localhost:3004'

policies:
  - cors
  - log
  - proxy
  - jwt

pipelines:
  authRegisterPipeline:
    apiEndpoints:
      - authRegister
    policies:
      - proxy:
          action:
            serviceEndpoint: authService
            changeOrigin: true

  authLoginPipeline:
    apiEndpoints:
      - authLogin
    policies:
      - proxy:
          action:
            serviceEndpoint: authService
            changeOrigin: true

  bookingCreatePipeline:
    apiEndpoints:
      - bookingCreate
    policies:
      # - jwt:
      #     action:
      #       secretOrPublicKey: ${JWT_SECRET}
      #       tokenKey: authorization
      #       credentialsRequired: true
      #       authScheme: Bearer
      - proxy:
          action:
            serviceEndpoint: bookingService
            changeOrigin: true
  
  bookingMyBookingsPipeline:
    apiEndpoints:
      - bookingMyBookings
    policies:
      # - jwt:
      #     action:
      #       secretOrPublicKey: ${JWT_SECRET}
      - proxy:
          action:
            serviceEndpoint: bookingService
            changeOrigin: true

  bookingAllBookingsPipeline:
    apiEndpoints:
      - bookingAllBookings
    policies:
      # - jwt:
      #     action:
      #       secretOrPublicKey: ${JWT_SECRET}
      - proxy:
          action:
            serviceEndpoint: bookingService
            changeOrigin: true

  bookingCancelPipeline:
    apiEndpoints:
      - bookingCancel
    policies:
      # - jwt:
      #     action:
      #       secretOrPublicKey: ${JWT_SECRET}
      - proxy:
          action:
            serviceEndpoint: bookingService
            changeOrigin: true
  theaterPipeline:
    apiEndpoints:
      - theaterApi
    policies:
      - cors:
          action:
            origin: '*'
            methods: 'GET,POST,PUT,DELETE'
            allowedHeaders: 'Content-Type,Authorization'
      - proxy:
          action:
            serviceEndpoint: theaterService
            changeOrigin: true

  showtimePipeline:
    apiEndpoints:
      - showtimeApi
    policies:
      - cors:
          action:
            origin: '*'
            methods: 'GET,POST,PUT,DELETE'
            allowedHeaders: 'Content-Type,Authorization'
      - proxy:
          action:
            serviceEndpoint: theaterService
            changeOrigin: true
  paymentInitiatePipeline:
    apiEndpoints:
      - paymentInitiate
    policies:
      # - jwt:
      #     action:
      #       secretOrPublicKey: ${JWT_SECRET}
      - proxy:
          action:
            serviceEndpoint: paymentService
            changeOrigin: true

  paymentConfirmPipeline:
    apiEndpoints:
      - paymentConfirm
    policies:
      # - jwt:
      #     action:
      #       secretOrPublicKey: ${JWT_SECRET}
      - proxy:
          action:
            serviceEndpoint: paymentService
            changeOrigin: true